#!/usr/bin/perl -w
# This file is part of g1sync.
#
# g1sync is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# g1sync is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You can download a copy of the GNU General Public License from
# <http://www.gnu.org/licenses/>.

use strict;
# music directory on the pc
my $PC_DIR="/mnt/mp3s/g1";
# music directory on the mobile device
my $MOBILE_DIR="/mnt/g1/music/sync";
# Kilobytes to KEEP_FREE on mobile device
my $KEEP_FREE="100000";

$_ = `df -k $MOBILE_DIR | tail -n1`;
/\s\d+\s+\d+\s+(\d+)\s/;
my $free = $1;

$_ = `du -sk $MOBILE_DIR`;
/^(\d+)[^\d]/;
my $mobileSize = $1;

#print "$free + $mobileSize - $KEEP_FREE\n";
print $free + $mobileSize - $KEEP_FREE;
