#!/usr/bin/perl -w
# This file is part of g1sync.
#
# g1sync is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# g1sync is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You can download a copy of the GNU General Public License from
# <http://www.gnu.org/licenses/>.

use strict;
# music directory on the pc
my $PC_DIR="/mnt/mp3s/g1";
# music directory on the mobile device
my $MOBILE_DIR="/mnt/g1/music/sync";
# directory where the playlists are generated
my $PLS_DIR="/mnt/g1/music/sync.m3u";
# relative path FROM_PLS_TO_MOBILE_DIR (for player to find music from m3u file)
my $FROM_PLS_TO_MOBILE_DIR="../sync/";
# files which should be include in the playlist (find syntax here)
my $FILETYPES="-name *.mp3 -or -name *.m4a -or -name *.mp4";

# find old files
open(MOBILE, "cd $MOBILE_DIR; find -type f $FILETYPES |") or die("Can't read $MOBILE_DIR");

my %onMOBILE;
while(<MOBILE>) {
	$onMOBILE{$_}++;
}
close(MOBILE);

# find new files
open(PC, "cd $PC_DIR; find -type f $FILETYPES |") or die("Can't read $PC_DIR");

# generate m3u filename
my ($sec,$min,$hour,$mday,$mon,$year,$wday,
$yday,$isdst)=localtime(time);
my $date_string=sprintf "%4d-%02d-%02d_%02d.%02d.%02d", $year+1900,$mon+1,$mday,$hour,$min,$sec;
my $pls="$PLS_DIR/$date_string.m3u";


open(M3U, ">$pls") or die("Can't write to $pls");

# write m3u file
while(<PC>) {
	if(! $onMOBILE{$_}) {
		/\.\/(.+)*$/;
		$_ = $1;
		print M3U $FROM_PLS_TO_MOBILE_DIR . $_ . "\n";
	}
}

close(M3U);

#system("cp", $pls, "$PLS_DIR/last.m3u") and die("Can't coppy $pls to $PLS_DIR/last.m3u");
