#!/usr/bin/perl -w
# This file is part of g1sync.
#
# g1sync is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# g1sync is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You can download a copy of the GNU General Public License from
# <http://www.gnu.org/licenses/>.

use strict;

# music directory on the pc
my $PC_DIR="/mnt/mp3s/g1";
# directory where old podcasts are moved to if they do not fit on the mobile device
my $ARCHIVE_DIR="/mnt/mp3s/g1.archive";


# If the size of the SD card $MAX_SIZE is exeeded move the oldest files to
# the archive $ARCHIVE_DIR. The $PC_DIR results in beeing smaller then $MAX_SIZE

my $MAX_SIZE;
if (defined $ARGV[0]) {
	$MAX_SIZE = $ARGV[0];
} else {
	print "usage: $0 <MAX_SIZE>\n";
	exit 2;
}


$_=`du -sk $PC_DIR`;
/^(\d+).+/;
my $curSize=$1;

if($curSize > $MAX_SIZE) {
	print "moving files to archive $ARCHIVE_DIR\n";
	open(OLDFILES, "find $PC_DIR -type f -printf ". '"%C@ %k %p\n"|sort|') or die("Can't find old files");
	while(<OLDFILES>) {
		/.+ (\d+) (.+)$/;
		my $size = $1;
		my $file = $2;
		$curSize = $curSize - $size;
		print "$size $file\n";
		
		$file =~ /$PC_DIR\/(.+)\/[^\/]*$/;
		my $dir = $1;

		system("mkdir", "-p", "$ARCHIVE_DIR/$dir") and die("Can't create directory $ARCHIVE_DIR/$dir");
		system("mv", "$file", "$ARCHIVE_DIR/$dir/") and die("Can't move file $file to $ARCHIVE_DIR/$dir");
		
		if($curSize < $MAX_SIZE) {
			last;
		}
	}
}
